Feature: Manage Users
  In order to manage the user data
  As an admin
  I want to create and manage users

  Scenario: User List
    Given I ...
    When I ...
    Then I ...
    And I ...

  Scenario: Create Valid Article
    Given I ...
    And I ...
    When I ...
    And I ...
    And I ...
    And I ...
    Then I ...
    And I ...
    And I ...
    And I ...